import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";
import typography from "@tailwindcss/typography";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        none: "0px",
        xs: "3px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        full: "9999px",
      },
      fontSize: {
        xi: "11px",
        xii: "12px",
        xiii: "13px",
        xiv: "14px",
        xvi: "16px",
        xviii: "18px",
        xx: "20px",
        xxiv: "24px",
        xxx: "30px",
        xxxvi: "36px",
      },
      colors: {
        // Flat / base colors (regular buttons)
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        ring: "hsl(var(--ring) / <alpha-value>)",
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)"
        },
        status: {
          online: "rgb(34 197 94)",
          away: "rgb(245 158 11)",
          busy: "rgb(239 68 68)",
          offline: "rgb(156 163 175)",
        },
        app: {
          bg: "var(--color-app-bg)",
          surface: "var(--color-app-surface)",
          card: "var(--color-app-card)",
          "card-hover": "var(--color-app-card-hover)",
          sunken: "var(--color-app-sunken)",
          overlay: "var(--color-app-overlay)",
          border: "var(--color-app-border)",
          "border-hover": "var(--color-app-border-hover)",
          "border-strong": "var(--color-app-border-strong)",
          "border-input": "var(--color-app-border-input)",
          text: "var(--color-app-text)",
          "text-muted": "var(--color-app-text-muted)",
          "text-subtle": "var(--color-app-text-subtle)",
          "text-faint": "var(--color-app-text-faint)",
          "text-inverse": "var(--color-app-text-inverse)",
          "text-link": "var(--color-app-text-link)",
          primary: "var(--color-app-primary)",
          "primary-hover": "var(--color-app-primary-hover)",
          "primary-active": "var(--color-app-primary-active)",
          "primary-dim": "var(--color-app-primary-dim)",
          "primary-border": "var(--color-app-primary-border)",
          "primary-text": "var(--color-app-primary-text)",
          "primary-disabled": "var(--color-app-primary-disabled)",
          secondary: "var(--color-app-secondary)",
          "secondary-hover": "var(--color-app-secondary-hover)",
          "secondary-active": "var(--color-app-secondary-active)",
          "secondary-border": "var(--color-app-secondary-border)",
          "secondary-text": "var(--color-app-secondary-text)",
          brand: "var(--color-app-brand)",
          "brand-hover": "var(--color-app-brand-hover)",
          "brand-dim": "var(--color-app-brand-dim)",
          "brand-border": "var(--color-app-brand-border)",
          "brand-text": "var(--color-app-brand-text)",
          success: "var(--color-app-success)",
          "success-hover": "var(--color-app-success-hover)",
          "success-dim": "var(--color-app-success-dim)",
          "success-border": "var(--color-app-success-border)",
          "success-text": "var(--color-app-success-text)",
          danger: "var(--color-app-danger)",
          "danger-hover": "var(--color-app-danger-hover)",
          "danger-dim": "var(--color-app-danger-dim)",
          "danger-border": "var(--color-app-danger-border)",
          "danger-text": "var(--color-app-danger-text)",
          warning: "var(--color-app-warning)",
          "warning-hover": "var(--color-app-warning-hover)",
          "warning-dim": "var(--color-app-warning-dim)",
          "warning-border": "var(--color-app-warning-border)",
          "warning-text": "var(--color-app-warning-text)",
          info: "var(--color-app-info)",
          "info-dim": "var(--color-app-info-dim)",
          "info-border": "var(--color-app-info-border)",
          "info-text": "var(--color-app-info-text)",
          hover: "var(--color-app-hover)",
          active: "var(--color-app-active)",
          selected: "var(--color-app-selected)",
          "selected-hover": "var(--color-app-selected-hover)",
          disabled: "var(--color-app-disabled)",
          "focus-ring": "var(--color-app-focus-ring)",
        },
        income: {
          bg: "var(--color-income-bg)",
          text: "var(--color-income-text)",
          border: "var(--color-income-border)",
        },
        expense: {
          bg: "var(--color-expense-bg)",
          text: "var(--color-expense-text)",
          border: "var(--color-expense-border)",
        },
        "status-draft": {
          bg: "var(--color-status-draft-bg)",
          text: "var(--color-status-draft-text)",
          border: "var(--color-status-draft-border)",
          dot: "var(--color-status-draft-dot)",
        },
        "status-sent": {
          bg: "var(--color-status-sent-bg)",
          text: "var(--color-status-sent-text)",
          border: "var(--color-status-sent-border)",
          dot: "var(--color-status-sent-dot)",
        },
        "status-paid": {
          bg: "var(--color-status-paid-bg)",
          text: "var(--color-status-paid-text)",
          border: "var(--color-status-paid-border)",
          dot: "var(--color-status-paid-dot)",
        },
        "status-void": {
          bg: "var(--color-status-void-bg)",
          text: "var(--color-status-void-text)",
          border: "var(--color-status-void-border)",
          dot: "var(--color-status-void-dot)",
        },
        "status-overdue": {
          bg: "var(--color-status-overdue-bg)",
          text: "var(--color-status-overdue-text)",
          border: "var(--color-status-overdue-border)",
          dot: "var(--color-status-overdue-dot)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        card: "var(--shadow-card)",
        modal: "var(--shadow-modal)",
        dropdown: "var(--shadow-dropdown)",
        input: "var(--shadow-input)",
        focus: "var(--shadow-focus)",
        "focus-error": "var(--shadow-focus-error)",
        button: "var(--shadow-button)",
      },
      transitionTimingFunction: {
        default: "var(--ease-default)",
        out: "var(--ease-out)",
        "in-out": "var(--ease-in-out)",
        spring: "var(--ease-spring)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
      },
      zIndex: {
        dropdown: "100",
        sticky: "200",
        overlay: "300",
        modal: "400",
        toast: "500",
        tooltip: "600",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate, typography],
} satisfies Config;
